# Generated by Django 5.2.7 on 2025-12-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='cod_dum',
            new_name='cod_dun',
        ),
    ]
